# READ MORE: https://www.spigotmc.org/wiki/plugin-yml/
name: ${project.name}
version: ${project.version}
main: io.protonull.civclassicglue.CivclassicGluePlugin
api-version: 1.16
depend: [CivModCore]
softdepend: []
author: Protonull
